export const customers = [{
    id: 1,
    name: "10 Roads Logistics",
    city: "Acton",
    state: "Maine",
    country: "United States",
    line1: "835 N. CENTRAL STREET",
    zip: "37917",
    phone: "+18669872077",
    mcnumber: "USD",
    dot_number: null,
    private_note: "Private Note here",
    public_note: null,
    contacts: [{
        id: 1, name: "Brent Carter", phone: "+18669872077", email: "Carter@Carter.com", fax: null, primary: 0,
    }, {
        id: 2, name: "Jody Spalding", phone: "+18669872077", email: "Spalding@Spalding.we", fax: null, primary: 1,
    },],
}, {
    id: 2,
    name: "Some new customer",
    city: "SHAKOPEE",
    state: "MN",
    country: "USA",
    line1: "1415 MARAS STREET SHAKOPEE, MN   55379",
    zip: "55379",
    phone: "+1(952) 445-8718",
    mcnumber: "440987",
    dot_number: null,
    private_note: "",
    public_note: "",
    contacts: [{
        id: 150, name: "name", phone: "234234234", email: null, fax: null, primary: true,
    },],
}, {
    id: 4,
    name: "Q CARRIERS LOGISTICS, INC.",
    city: "SHAKOPEE",
    state: "MN",
    country: "USA",
    line1: "1415 MARAS STREET",
    zip: "55379",
    phone: "952-697-4445",
    mcnumber: "440987",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 5, name: null, phone: "952-697-4445", email: null, fax: null, primary: true,
    },],
}, {
    id: 5,
    name: "Arrive Logistics",
    city: "Austin",
    state: "TX",
    country: "USA",
    line1: "7701 Metropolis Dr | Bldg 15",
    zip: "78744",
    phone: "888-861-0650",
    mcnumber: "787104",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 6, name: "Arrive Logistics", phone: "888-861-0650", email: null, fax: null, primary: true,
    },],
}, {
    id: 6,
    name: "Redwood Logistics",
    city: "LOUISVILLE",
    state: "KY",
    country: "USA",
    line1: "PO Box 701059",
    zip: "40209",
    phone: "3126988278",
    mcnumber: "412533",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 7,
        name: "Redwood Logistics",
        phone: "3126988278",
        email: "kcluxton@redwoodlogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 7,
    name: "Tallgrass Freight Co.",
    city: "Shawnee",
    state: "KS",
    country: "USA",
    line1: "6800 Hilltop Rd, St 202",
    zip: "66226",
    phone: "913-721-0079",
    mcnumber: "803256",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 8,
        name: "Aaron Bending",
        phone: "913-721-0079",
        email: "aberding@tallgrassfreight.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 8,
    name: "Surge Transportation Inc.",
    city: "Jacksonville",
    state: "FL",
    country: "USA",
    line1: "6001 Argyle Forest Blvd St 21-342",
    zip: "32244",
    phone: "844-591-6090",
    mcnumber: "518710",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 9,
        name: "Lindsay",
        phone: "844-591-6090",
        email: "lindsay.baar@surgetransportation.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 9,
    name: "Total Quality Logisitcs TQL",
    city: "Milford",
    state: "OH",
    country: "USA",
    line1: "P.O. Box 799",
    zip: "45150",
    phone: "800-580-3101",
    mcnumber: "322572",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 10,
        name: "Total Quality Logisitcs TQL",
        phone: "800-580-3101",
        email: "JHerrera@TQL.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 10,
    name: "Manufacturers Transportation Inc.",
    city: "McKinney",
    state: "TX",
    country: "USA",
    line1: "P.O. Box 557",
    zip: "75070",
    phone: "972-562-8686",
    mcnumber: "172707",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 11,
        name: "Adam  Robinson",
        phone: "972-562-8686",
        email: "adam@manutransport.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 11,
    name: "Integrity Express Logistics",
    city: "Cincinnati",
    state: "OH",
    country: "USA",
    line1: "P.O. Box 42275",
    zip: "45242",
    phone: "937-483-5344",
    mcnumber: "596655",
    dot_number: null,
    private_note: "",
    public_note: "",
    contacts: [{
        id: 12, name: "Madison", phone: "937-483-5344", email: "mlschaerges@intexlog.com", fax: null, primary: true,
    },],
}, {
    id: 12,
    name: "Edge Logistics LLC",
    city: "Chicago",
    state: "IL",
    country: "USA",
    line1: "333 N Michigan Ave",
    zip: "60601",
    phone: "312-319-4766",
    mcnumber: "873427",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 13,
        name: "Nick Petruska",
        phone: "312-319-4766",
        email: "npetruska@edgelogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 13,
    name: "Allen Lund Company",
    city: "La Canada",
    state: "CA",
    country: "USA",
    line1: "P.O. Box 339",
    zip: "91012",
    phone: "843-606-6272",
    mcnumber: "163523",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 14, name: "Sadie", phone: "800-870-5863", email: "sadie.corle@allenlund.com", fax: null, primary: true,
    },],
}, {
    id: 14,
    name: "Dupre Logisitcs LLC",
    city: "Lafayette",
    state: "LA",
    country: "USA",
    line1: "201 Energy Parkway",
    zip: "70508",
    phone: "844-452-8980",
    mcnumber: "158069",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 15,
        name: "Melissa Torres",
        phone: "844-452-8980",
        email: "nwaoperations@duprelogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 15,
    name: "XPO Logistics Inc.",
    city: "Charlotte",
    state: "NC",
    country: "USA",
    line1: "P.O. Box 49069",
    zip: "28210",
    phone: "330-745-0031",
    mcnumber: "175953",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 16,
        name: "XPO Logistics Inc.",
        phone: "330-745-0031",
        email: "samuel.hinze@xpo.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 16,
    name: "Hwy Haul",
    city: "Santa Clara",
    state: "CA",
    country: "USA",
    line1: "900 Lafayette St, Suite 307",
    zip: "95050",
    phone: "855-499-4285",
    mcnumber: "131593",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 17, name: "Ahmed", phone: "855-499-4285", email: "contact@hwyhaul.com", fax: null, primary: true,
    },],
}, {
    id: 17,
    name: "Axle Logistics LLC",
    city: "Knoxville",
    state: "TN",
    country: "USA",
    line1: "835 N.Central Street",
    zip: "37917",
    phone: "800-693-1779",
    mcnumber: "765587",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 18,
        name: "Spencer Bobrowski",
        phone: "800-693-1779",
        email: "spencer.bobrowski@axlelogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 18,
    name: "Sage Freight",
    city: "Franklin",
    state: "TN",
    country: "USA",
    line1: "840 Crescent Centre Drive, Suite 120",
    zip: "37067",
    phone: "(877) 323-7243",
    mcnumber: "1186372-B",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 19,
        name: "Sam Burns",
        phone: "(877) 323-7243",
        email: "sam.burns@sagefreight.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 19,
    name: "Walker Transportation Services Inc",
    city: "Grottoes",
    state: "VA",
    country: "USA",
    line1: "93 Grace Street Grottoes VA",
    zip: "24441",
    phone: "(540) 209-9899",
    mcnumber: "372373",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 20,
        name: "Walker Transportation Services Inc",
        phone: "(540) 209-9899",
        email: null,
        fax: null,
        primary: true,
    },],
}, {
    id: 20,
    name: "Traffic Tech Inc",
    city: "Chicago",
    state: "IL",
    country: "United States",
    line1: "111 E. Wacker Drive, Ste 2500",
    zip: "60601",
    phone: "312-465-1440",
    mcnumber: "330574",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 21, name: "Traffic Tech Inc", phone: "312-465-1440", email: "P@traffictech.com", fax: null, primary: true,
    },],
}, {
    id: 21,
    name: "Volta Logistics",
    city: "Minneapolis",
    state: "MN",
    country: "USA",
    line1: "1515 Central AVE NE Suite 120",
    zip: "55413",
    phone: "612-356-5560",
    mcnumber: "895437",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 22,
        name: "Anton Alekseyev",
        phone: "240-650-0321",
        email: "aalekseyev@voltalogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 22,
    name: "SpartanNash Logistics",
    city: "Indianapolis",
    state: "IN",
    country: "USA",
    line1: "5752 Wheeler Rd",
    zip: "46216",
    phone: "317-600-2300",
    mcnumber: "222986",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 23,
        name: "Amira.Strang",
        phone: "317-600-2300",
        email: "Amira.Strang@spartannash.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 23,
    name: "C Cross Logistics",
    city: "Tuscaloosa AL",
    state: "AL",
    country: "USA",
    line1: "PO Box 1998",
    zip: "35403",
    phone: "205-937-8735",
    mcnumber: "724981",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 24,
        name: "Faulkner Williams",
        phone: "205-937-8735",
        email: "FWilliams@ccrosslogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 24,
    name: "ATL Logistics Management Inc",
    city: "Tucker",
    state: "GA",
    country: "United States",
    line1: "1798 MONTREAL CIR SUITE 201",
    zip: "30084",
    phone: "(770)-939-1532",
    mcnumber: "840468",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 25, name: "John", phone: "770-939-1508", email: "john.avci@atltransport.net", fax: null, primary: true,
    },],
}, {
    id: 25,
    name: "Watco Supply Chain Services LLC",
    city: "Springdale",
    state: "AR",
    country: "USA",
    line1: "3905 Elliot Ave",
    zip: "72762",
    phone: "479-347-7240",
    mcnumber: "430294",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 26, name: "Michael Kolec", phone: "479-347-7240", email: "mike.kolec@watco.com", fax: null, primary: true,
    },],
}, {
    id: 26,
    name: "ODW LTS,LLC",
    city: "Hamilton",
    state: "OH",
    country: "United States",
    line1: "345 High Street Suite #600",
    zip: "45011",
    phone: "800-978-3168",
    mcnumber: "679673",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 27,
        name: "Erin Morehead",
        phone: "800.978.3168x1777",
        email: "Erin.Morehead@odwlogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 27,
    name: "Direct Traffic Solutions",
    city: "Boca Raton",
    state: "FL",
    country: "United States",
    line1: "7491 N FEDERAL HWY STE C5",
    zip: "33487",
    phone: "(732) 515-6108",
    mcnumber: "423054",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 28, name: "Direct Traffic Solutions", phone: "(732) 515-6108", email: null, fax: null, primary: true,
    },],
}, {
    id: 28,
    name: "J.Gust Transportation Inc",
    city: "Clovis",
    state: "CA",
    country: "United States",
    line1: "ODFL 6925 SE FOUR MILE DRIVE ANKENY IA",
    zip: "50021",
    phone: "(559) 323-7403",
    mcnumber: "929989",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 29, name: "Randy Botello", phone: "559-323-7403", email: "randy@gusttrucking.com", fax: null, primary: true,
    },],
}, {
    id: 29,
    name: "AMX Logistics",
    city: "Ashford",
    state: "AL",
    country: "USA",
    line1: "PO Box 487",
    zip: "36312",
    phone: "334-699-2790",
    mcnumber: "196425",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 30,
        name: "AMX Logistics",
        phone: "334-699-2790",
        email: "twhelan@amxtrucking.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 30,
    name: "Travero Logistics",
    city: "CEDAR RAPIDS",
    state: "IA",
    country: "USA",
    line1: "PO BOX 1173",
    zip: "52406",
    phone: "608-205-1883",
    mcnumber: "441429",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 31, name: "Travero Logistics", phone: "608-205-1883", email: null, fax: null, primary: true,
    },],
}, {
    id: 31,
    name: "Schneider Freight Power",
    city: "Louisville",
    state: "KY",
    country: "USA",
    line1: "P.O. BOX 9569",
    zip: "40209",
    phone: "920-357-8987",
    mcnumber: "133655",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 32, name: "Derek White", phone: "920-357-8987", email: "WhiteD5@schneider.com", fax: null, primary: true,
    },],
}, {
    id: 32,
    name: "Armstrong Transport Group",
    city: "Charlotte",
    state: "NC",
    country: "USA",
    line1: "8615 CLIFF CAMERON DR SUITE 200",
    zip: "28269",
    phone: "888-315-5932",
    mcnumber: "555609",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 33,
        name: "Armstrong Transport Group",
        phone: "888-315-5932",
        email: "nhaldi@armstrongtransport.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 33,
    name: "STS Logistics",
    city: "Smyrna",
    state: "TN",
    country: "USA",
    line1: "225 SAM GRIFFIN ROAD",
    zip: "37167",
    phone: "(615) 622-0912",
    mcnumber: "299061",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 34,
        name: "STS Logistics",
        phone: "(615) 622-0912",
        email: "travis.french@shipsts.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 34,
    name: "Fusion Transport LLC",
    city: "Glen Rock",
    state: "NJ",
    country: "USA",
    line1: "208 Harristown Road, Suite 201",
    zip: "07452",
    phone: "(201) 857-9347",
    mcnumber: "937172",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 35,
        name: "Ed Geiger",
        phone: "(201) 857-9347",
        email: "egeiger@fusiontransport.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 35,
    name: "TransLoop",
    city: "Chicago",
    state: "IL",
    country: "USA",
    line1: "343 W. ERIE SUITE #520",
    zip: "60654",
    phone: "(815) 916-5667",
    mcnumber: "862463",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 36,
        name: "Dominick Bartemio",
        phone: "(815) 916-5667",
        email: "Dominick.Bartemio@Transloop.io",
        fax: null,
        primary: true,
    },],
}, {
    id: 36,
    name: "Epes Logistics",
    city: "Greensboro",
    state: "NC",
    country: "USA",
    line1: "PO Box 35884",
    zip: "27425",
    phone: "866-248-3471",
    mcnumber: "211123",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 37,
        name: "Elizabeth DiNatali",
        phone: "866-248-3471",
        email: "elizabeth.dinatali@epeslogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 37,
    name: "Nolan Transport Group LLC",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    line1: "1735 Founders Parkway Suite 300",
    zip: "30009",
    phone: "(616) 827-4622",
    mcnumber: "567093",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 38,
        name: "TREY GORDON",
        phone: "(470) 826-2435 Ext 3155",
        email: "TREY.GORDON@NTGFREIGHT.COM",
        fax: null,
        primary: true,
    },],
}, {
    id: 38,
    name: "Scotlynn USA Division",
    city: "Fort Myers",
    state: "FL",
    country: "USA",
    line1: "9597 Gulf Research Lane",
    zip: "33912",
    phone: "888-263-1888",
    mcnumber: "710411",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 39,
        name: "Anastasia Dempsey",
        phone: "239-236-7462",
        email: "adempsey@scotlynn.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 39,
    name: "Cheema Logistics",
    city: "Sumner",
    state: "WA",
    country: "USA",
    line1: "PO Box 2234",
    zip: "98399",
    phone: "253-244-9247",
    mcnumber: "681109",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 40,
        name: "Kathy Jones",
        phone: "(406) 542-8390 x4147",
        email: "kjones@cheemalogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 40,
    name: "Vital Worldwide  Logistics Corporation",
    city: "Edison",
    state: "NJ",
    country: "USA",
    line1: "23 mack dr. suite 102",
    zip: "08818",
    phone: "732-447-2789",
    mcnumber: "936891",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 41, name: "Maya", phone: "732) 447-2789 ext.102", email: "dispatch@vwlcorp.com", fax: null, primary: true,
    },],
}, {
    id: 41,
    name: "BNSF Logistics",
    city: "Versailles",
    state: "OH",
    country: "USA",
    line1: "PO Box 176",
    zip: "45380",
    phone: "(800) 458-7224",
    mcnumber: "39484",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 42, name: "BNSF Logistics", phone: "(800) 458-7224", email: null, fax: null, primary: true,
    },],
}, {
    id: 42,
    name: "Trinity Logistics",
    city: "Seaford",
    state: "FL",
    country: "DE",
    line1: "P.O. BOX 1620",
    zip: "19973",
    phone: "(843) 209-1461",
    mcnumber: "205157",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 43,
        name: "RANDALL ROBERSON",
        phone: "(843) 209-1461",
        email: "RANDALL.ROBERSON@trinitylogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 43,
    name: "FLEXX FREIGHT INC",
    city: "Bridgeview",
    state: "IL",
    country: "USA",
    line1: "8711 S 77th Ave",
    zip: "60455",
    phone: "(773) 897-3100",
    mcnumber: "1004564",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 44,
        name: "OPERATIONS FLEXX FREIGHT",
        phone: "773 897-3100",
        email: "ops@flexxfreight.us",
        fax: null,
        primary: true,
    },],
}, {
    id: 44,
    name: "Mid America Logistics",
    city: "Fenton",
    state: "MO",
    country: "USA",
    line1: "44 Soccer Park Road",
    zip: "63026",
    phone: "636 492 5962",
    mcnumber: "655734",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 45,
        name: "Mid America Logistics",
        phone: "636 492 5962",
        email: "jerry.nunez@midamlogistics.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 45,
    name: "Echo",
    city: "Chicago",
    state: "IL",
    country: "USA",
    line1: "600 W. Chicago Ave #725 Chicago IL 60610",
    zip: "60610",
    phone: "(855) 786-3246",
    mcnumber: "511639",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 46, name: "Echo", phone: "(855) 786-3246", email: null, fax: null, primary: true,
    },],
}, {
    id: 46,
    name: "FLS Transport Services Limited",
    city: "Rome GA",
    state: "QC",
    country: "USA",
    line1: "PO Box 391",
    zip: "30162",
    phone: "(877) 823-0036 x7018",
    mcnumber: "208433",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 47,
        name: "Jamie Curtis",
        phone: "(877) 823-0036 x7018",
        email: "jcurtis@flstransport.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 47,
    name: "Old Dominion Freight Line,Inc",
    city: "Dallas",
    state: "TX",
    country: "USA",
    line1: "PO BOX 841324",
    zip: "75284",
    phone: "877-562-3875",
    mcnumber: "107478",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 48,
        name: "Old Dominion Freight Line,Inc",
        phone: "877-562-3875",
        email: "TRUCKLOAD.SERVICES@ODFL.COM",
        fax: null,
        primary: true,
    },],
}, {
    id: 48,
    name: "R&R Express Logistics Inc",
    city: "Pittsburgh",
    state: "PA",
    country: "USA",
    line1: "100 COMMERCE DRIVE PITTSBURGH, PA 15275",
    zip: "15275",
    phone: "412-778-8255",
    mcnumber: "297351",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 49,
        name: "Zachary Cortese",
        phone: "412-778-8255",
        email: "zachary.cortese@shiprrexp.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 49,
    name: "Gulf Coast Logistics",
    city: "Mandeville",
    state: "LA",
    country: "USA",
    line1: "P.O. BOX 2471",
    zip: "70470",
    phone: "985-727-4064",
    mcnumber: "412496",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 50,
        name: "Gulf Coast Logistics",
        phone: "985-727-4064",
        email: "GALEXIS@GULFCOASTLOGISTICS.COM",
        fax: null,
        primary: true,
    },],
}, {
    id: 50,
    name: "RFX Inc",
    city: "Quincy",
    state: "MA",
    country: "USA",
    line1: "1250 Hancock Street Ste 760N",
    zip: "02169",
    phone: "908-234-0245",
    mcnumber: "203507",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 51,
        name: "Erin Bouziotis",
        phone: "908-234-0245",
        email: "e.bouzioyis@Rfxinc.com",
        fax: null,
        primary: true,
    },],
}, {
    id: 51,
    name: "KLC Logistics Inc",
    city: "Omaha",
    state: "NE",
    country: "USA",
    line1: "9829 S 168th Ave Ste 4E",
    zip: "68136",
    phone: "(217)469-2158",
    mcnumber: "206646",
    dot_number: null,
    private_note: null,
    public_note: null,
    contacts: [{
        id: 52, name: "KLC Logistics Inc", phone: "(217)469-2158", email: null, fax: null, primary: true,
    },],
},];
