export const loadsForm = [{
    advance: null,
    advance_fee: null,
    customer: {
        city: "SHAKOPEE",
        contacts: [{id: 150, name: "name", phone: "234234234", email: null, fax: null, primary: 1}],
        country: "USA",
        dot_number: null,
        id: 2,
        line1: "1415 MARAS STREET SHAKOPEE, MN   55379",
        mcnumber: "440987",
        name: "Some new customer",
        phone: "+1(952) 445-8718",
        private_note: "",
        public_note: "",
        state: "MN",
        zip: "55379",
    },
    deduction: null,
    delivery_date: "2022-03-16",
    delivery_time: null,
    detention_pay: null,
    distance: 1177,
    driver: {
        address: "10800 S 13th St, Oak Creek, WI 53154",
        first_name: "Marquez",
        id: 7,
        last_name: "Floyd",
        power_unit_id: 10,
        trailer_id: 6,
    },
    dropAddress: {
        address: "400 Walker St, Houston, TX 77002, United States",
        admindistrict: "TX",
        city: "Downtown Houston",
        id: 714,
        zip_code: "77002",
    },
    lumper_fee: null,
    order_number: "2347143",
    pickAddress: {
        address: "100 W Vandalia St, Edwardsville, IL 62025, United States",
        admindistrict: "IL",
        city: "Edwardsville",
        id: 715,
        zip_code: "62025"
    },
    pickup_date: "2022-03-15",
    pickup_time: null,
    power_unit: 1,
    price: "2700",
    price_other: null,
    reference_number: "",
    tonu: 0,
    trailer: 1,
},
];
